### ISSUE TITLE
Не получается распасрить правильно метод wall.get

### ISSUE THREAD

**Issue by SequelONE** [atehnix/vk-client#1]
Здравствуйте. Есть проблема с парсингом API vk.com на Laravel 5.3 
Вот вид моего виджета NewsVK:

```
public function run()
    {
        $api = new Client;

        $wallget = $api->request('wall.get', [
            'owner_id'       => '-12370608',
            'domain'    => 'realtatish',
            'filter'    => 'all',
            'offset'    => '0',
            'count'     => '5'
        ]);
        
        $wallget = $wallget["response"]["items"];

        foreach($wallget as $i) {
            echo '<pre>';
            var_dump($i["is_pinned"]);
        }
            
        return view("widgets.news_v_k", [
            'wallget' => $wallget,
            'config' => $this->config,
        ]);
    }
```

Из массива нормально парсяться поля ["text"], ["date"], но когда пытаюсь или через foreach вывести или же просто указывать как переменную $attachments = $i["attachments"] (в шаблоне конечно через foreach вывод идёт), но при упоминании полей ["attachments"] или ["is_pinned"] вываливается ошибка Undefined index: is_pinned

Подскажите пожалуйста как проверять наличие поля ["attachments"]? Я так понимаю это из-за того, что некоторые посты содержать прикреплённые файлы, а некоторые нет, надо тогда отлавливать название этого массива вложенного?!

**Comment by SequelONE** [comment]
`if(!isset($i["attachments"])){die('Нет данных!');}`

Вот что значит не выспался, извените за беспокойство)

**Comment by ghost** [comment]
Ничего страшного, рад что проблема решилась. ;)
